# Generated by Django 3.2.5 on 2021-09-13 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2083)),
                ('title', models.CharField(max_length=200)),
                ('pay', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('board', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('radius', models.CharField(max_length=3)),
            ],
        ),
    ]
